// protoc --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative ./api/grpc/*.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/grpc/example.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FooBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FooBarRequest) Reset() {
	*x = FooBarRequest{}
	mi := &file_api_grpc_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FooBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooBarRequest) ProtoMessage() {}

func (x *FooBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FooBarRequest.ProtoReflect.Descriptor instead.
func (*FooBarRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_example_proto_rawDescGZIP(), []int{0}
}

func (x *FooBarRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type FooBarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []int64                `protobuf:"varint,1,rep,packed,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FooBarResponse) Reset() {
	*x = FooBarResponse{}
	mi := &file_api_grpc_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FooBarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooBarResponse) ProtoMessage() {}

func (x *FooBarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FooBarResponse.ProtoReflect.Descriptor instead.
func (*FooBarResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_example_proto_rawDescGZIP(), []int{1}
}

func (x *FooBarResponse) GetData() []int64 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_grpc_example_proto protoreflect.FileDescriptor

const file_api_grpc_example_proto_rawDesc = "" +
	"\n" +
	"\x16api/grpc/example.proto\x12\aExample\x1a\x1bgoogle/protobuf/empty.proto\"#\n" +
	"\rFooBarRequest\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\"$\n" +
	"\x0eFooBarResponse\x12\x12\n" +
	"\x04Data\x18\x01 \x03(\x03R\x04Data2M\n" +
	"\x0eExampleService\x12;\n" +
	"\x06FooBar\x12\x16.Example.FooBarRequest\x1a\x17.Example.FooBarResponse\"\x00B\x11Z\x0fexample/exampleb\x06proto3"

var (
	file_api_grpc_example_proto_rawDescOnce sync.Once
	file_api_grpc_example_proto_rawDescData []byte
)

func file_api_grpc_example_proto_rawDescGZIP() []byte {
	file_api_grpc_example_proto_rawDescOnce.Do(func() {
		file_api_grpc_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_example_proto_rawDesc), len(file_api_grpc_example_proto_rawDesc)))
	})
	return file_api_grpc_example_proto_rawDescData
}

var file_api_grpc_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_grpc_example_proto_goTypes = []any{
	(*FooBarRequest)(nil),  // 0: Example.FooBarRequest
	(*FooBarResponse)(nil), // 1: Example.FooBarResponse
}
var file_api_grpc_example_proto_depIdxs = []int32{
	0, // 0: Example.ExampleService.FooBar:input_type -> Example.FooBarRequest
	1, // 1: Example.ExampleService.FooBar:output_type -> Example.FooBarResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_example_proto_init() }
func file_api_grpc_example_proto_init() {
	if File_api_grpc_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_example_proto_rawDesc), len(file_api_grpc_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_example_proto_goTypes,
		DependencyIndexes: file_api_grpc_example_proto_depIdxs,
		MessageInfos:      file_api_grpc_example_proto_msgTypes,
	}.Build()
	File_api_grpc_example_proto = out.File
	file_api_grpc_example_proto_goTypes = nil
	file_api_grpc_example_proto_depIdxs = nil
}
